config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  resources :customers
  resources :sites, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :products
  resources :devices

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  #ASSOCIATIONS
  has_many :sites
  has_many :products
  has_many :devices

  #VALIDATION
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :code, presence: true, uniqueness: {case_sensitive: false}
end

app/models/site.rb
class Site < ActiveRecord::Base
  #ASSOCIATIONS
  belongs_to :customer

  #VALIDATION
  validates :name, presence: true
  validates :code, presence: true
  validates :customer_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path
    else
      render 'new'
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.paginate(page: params[:page], :per_page => 5)
  end

  def update
  end

  def destroy
  end


  # DEFINE PARAMETERS
  private
  def customer_params
    params.require(:customer).permit(:name, :code)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def new
    @customer = Customer.find(params[:customer])
    @site = Site.new
  end

  def create
    @customer = Customer.find(params[:customer])
    @site = @customer.sites.build(site_params)
    if @site.save
      flash[:success] = "Site Created"
      redirect_to customer_path(@customer)
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @site = Site.find(params[:id])
    @customer = @site.customer
  end

  def index
  end

  def update
  end

  def destroy
  end


  #DEFINE PARAMETERS
  private
  def site_params
    params.require(:site).permit(:name, :code, :site_type, :total_users)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Solution Designer"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/customers/_customer.html.erb
<li>
  <%= link_to customer.name, customer %>
</li>

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customers/index.html.erb
<% provide :title, "All Customers" %>
<h1>All Customers</h1>
<%= link_to "Add New Customer", new_customer_path %>
<ul class="customers">
  <%= render @customers %>
</ul>

app/views/customers/new.html.erb
<% provide :title, 'New Customer' %>
<h1>Create Customer</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@customer) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :code %>
        <%= f.text_field :code, class: 'form-control' %>
        <%= f.submit "Create Customer", class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/customers/show.html.erb
<% provide :title, @customer.name %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1><%= @customer.name %></h1>
      Customer Code: <%= @customer.code %>
    </section>
  </aside>
  <div class="col-md-8">
    SITES:
    <%= link_to "Create New Site", new_site_path(:customer => @customer.id) %>
    <ol class="sites">
      <%= render @customer.sites %>
    </ol>
  </div>
  <div class="col-md-8">
    PRODUCTS:
    <%= link_to "Create New Product", new_product_path(:customer => @customer.id) %>
    <ol class="products">
      <%= @customer.products.each do |product| %>

          <%= render product %>
          DEVICES:
          <ul>
            <%= render product.devices %>
          </ul>
      <% end %>


    </ol>
  </div>
</div>

app/views/devices/_device.html.erb
<li>
  <%= link_to device.name, device %>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Designer Test
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Home", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Customers", customers_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">

  <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>


  <%= yield %>



  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/products/_product.html.erb
<li>
  <%= link_to product.name, product %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/sites/_site.html.erb
<li>
  <%= link_to site.name, site %>
</li>

app/views/sites/edit.html.erb
<h1>Sites#edit</h1>
<p>Find me in app/views/sites/edit.html.erb</p>

app/views/sites/index.html.erb
<h1>Sites#index</h1>
<p>Find me in app/views/sites/index.html.erb</p>

app/views/sites/new.html.erb
<% provide(:title, @customer.name) %>
<h1>Create New Site</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@site) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name, class:'form_control' %>
        <%= f.label :code %>
        <%= f.text_field :code, class:'form_control' %>
        <%= f.label :site_type %>
        <%= f.text_field :site_type, class:'form_control' %>
        <%= f.label :total_users %>
        <%= f.text_field :total_users, class:'form_control' %>
        <%= f.submit "Create Site", class:"btn btn-primary" %>
        <%= hidden_field_tag :customer, @customer.id %>
    <% end %>
  </div>
</div>

app/views/sites/show.html.erb
<% provide :title, @customer.name %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1><%= link_to @customer.name, customer_path(@site.customer) %></h1>
    </section>
  </aside>
  <div class="col-md-8">
    <p> Site Name: <%= @site.name %> </p>
    <p> Site Code: <%= @site.code %> </p>
    <p> Site Type: <%= @site.site_type %> </p>
    <p> Total Users: <%= @site.total_users %> </p>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide :title, "Help" %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Home</h1>
<p>
       Welcome to the Solution Designer
</p>